language: ruby
rvm:
  - "2.1.1"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/application.travis.yml config/application.yml
  - psql -c 'create database coursewareofthefuture_test;' -U postgres
  - psql -U postgres -q -d coursewareofthefuture_test -f db/structure.sql

script: 'REPORT_COVERAGE=true bundle exec rake'
